services:
  frontend:
    metrics:
      statsd: ~
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:8000"

  matching:
    metrics:
      statsd: ~
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:8001"

  history:
    metrics:
      statsd: ~
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:8002"

  worker:
    metrics:
      statsd: ~
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:8003"

  shard-distributor:
    metrics:
      statsd: ~
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:8004"
